<?php

    return array(
        'home'          =>  'homepage',
        'homemenu'          =>  'Homepage',
        'presentation'  =>  'Presentation',
        'presentationmenu'  =>  'Presentation',
        'shows'         =>  'shows',
        'showsmenu'         =>  'Shows',
        'program'       =>  'Program',
        'exhibitions'   =>  'exhibitions',
        'exhibitionsmenu'   =>  'Exhibitions',
        'workshops'     =>  'Workshops',
        'workshopsmenu' =>  'Workshops',
        'conferences'   =>  'conferences',
        'conferencesmenu'   =>  'Conferences',
        'documents'     =>  'Documents',
        'manifest'      =>  'manifest',
        'manifestmenu'      =>  'Manifest',
        'archieve'      =>  'archieve',
        'archievemenu'  =>  'Archieve',
        'articles'      =>  'articles',
        'articlesmenu'      =>  'Articles',
        'press'         =>  'Newsroom',
        'pressmenu'     =>  'Newsroom',
        'crew'          =>  'crew',
        'crewmenu'          =>  'Crew',
        'places'        =>  'venues',
        'placesmenu'    =>  'Venues',
        'supporters'    =>  'supporters',
        'supportersmenu'    =>  'Supporters',
        'contact'       =>  'Contact',
        'contactmenu'   =>  'Contact',
        'groups'        =>  'Groups',
        'group_name'    =>  'Group Name',
        'show_name'     =>  'Show Name',
        'language'      =>  'Language',
        'age'           =>  'Age',
        'duration'      =>  'Duration',
        'about'         =>  'About',
        'type'          =>  'Type',
        'delete'        =>  'Delete',
        'edit'          =>  'Edit',
        'program'       =>  'Program',
        'programmenu'   =>  'Program',
        'backtoshows'   =>  'Back To Shows'

    );